spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://ktaunk28:3570@cluster0.enqct.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: udharDO
  main:
    allow-circular-references: true